sonar.projectKey=ds-video-qc:data-science
sonar.projectName=ds-video-qc
sonar.sourceEncoding=UTF-8
sonar.language=py
sonar.projectVersion=1.0.0
sonar.host.url=https://sonar.gdn-app.com
sonar.sources=.
sonar.exclusions=configs/*, src/components/pub_sub.py, src/application/app.py